### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by JBorras-summar** [MicrosoftDocs/visualstudio-docs.es-es#30]
- (ENGLISH) Link to "MPN Program Administrator Guide" does not work.
- (SPANISH) No funciona el enlace a "MPN Program Administrator Guide".
https://assetsprod.microsoft.com/en-us/Program-Administrator-Guide-to-Software-and-Online-Services-Benefits_1.pdf

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c7f04b1d-cc98-8383-82cc-67b1be25d3ca
* Version Independent ID: e4855453-e4ed-7eb6-dbf3-5da7e79298ea
* Content: [Suscripciones de Visual Studio ofrecidas a partners de Microsoft Partner Network (MPN)](https://docs.microsoft.com/es-es/visualstudio/subscriptions/program-mpn#feedback)
* Content Source: [subscriptions/program-mpn.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/subscriptions/program-mpn.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by CeciAc** [comment]
Hello, @JBorras-summar 
Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5292

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
